name: Build, Test, and Deploy

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node Version
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Build and package library
        run: |
          npm run package --if-present
        env:
          CI: true

      - name: Format
        run: |
          npm run format:check --if-present
        env:
          CI: true

      - name: Build
        run: |
          npm run build --if-present
        env:
          CI: true

      - name: Test
        run: |
          npm run ci --if-present
        env:
          CI: true

      - name: Trigger Repository Siemens Datatable Workflow
        if: always() # Runs even if Test step fails
        env:
          PAT: ${{ secrets.PLAYWRIGHT }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $PAT" \
            https://api.github.com/repos/chintankavathia/siemens-datatable/actions/workflows/test_and_deploy.yml/dispatches \
            -d '{"ref":"test/setup-playwright"}'

      - name: Build Docs
        run: |
          npm run build-docs --if-present
        env:
          CI: true

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist/ngx-datatable
        if: ${{ github.ref == 'refs/heads/master' }}
