name: Build, Test, and Deploy

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node Version
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron

      - name: Pull Repository with LFS
        run: git lfs pull

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Build and package library
        run: |
          npm run package --if-present
        env:
          CI: true

      - name: Format
        run: |
          npm run format:check --if-present
        env:
          CI: true

      - name: Build
        run: |
          npm run build --if-present
        env:
          CI: true

      - name: Test
        run: |
          npm run ci --if-present
        env:
          CI: true

      - name: E2E
        uses: addnab/docker-run-action@v3
        with:
          image: mcr.microsoft.com/playwright:v1.46.0-jammy
          options: --ipc=host -v ${{ github.workspace }}:/workspace -w /workspace
          run: |
            npm run e2e --if-present
        env:
          CI: true

      - name: Upload E2E Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-results
          path: playwright/results

      - name: Build Docs
        run: |
          npm run build-docs --if-present
        env:
          CI: true

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist/ngx-datatable
        if: ${{ github.ref == 'refs/heads/master' }}
